/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/ui/theme/mysp-theme.ts
 * Command: astryx theme build src/ui/theme/mysp-theme.ts
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/// <reference path="./mysp.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const myspTheme: DefinedTheme;
