/**
 * Generates `src/ui/theme/presets.css` from the preset table in
 * `src/shared/appearance-presets.ts`.
 *
 *   pnpm run theme:presets          write the stylesheet
 *   pnpm run theme:presets --check  fail if the committed file is stale
 *
 * WHY GENERATE INSTEAD OF HAND-WRITING THE CSS: the same six presets have to be
 * known by the stylesheet, by the usecase that validates what is stored, and by
 * the screen that draws the swatches. Hand-copying colours into CSS is the
 * second table that drifts (web-design-tokens §1: CSS variable là NƠI TIÊU THỤ,
 * không phải nguồn). `presets.generated.test.ts` runs the --check so a stale
 * file fails `pnpm verify` rather than shipping a swatch whose colour is a lie.
 *
 * WHY ATTRIBUTE SCOPES AND NOT AN INLINE `<style>` FROM THE SERVER: an inline
 * block would have to out-specify `:root` AND `.dark` by cascade order, which
 * is decided by where Next happens to put the tag. `:root[data-theme-preset=…]`
 * beats `:root` on specificity alone, `:root.dark[data-theme-preset=…]` beats
 * both, and the whole thing is a static stylesheet the browser already has
 * before first paint — so there is no flash to fix (the trap `mysp-theme.ts`
 * documents for runtime themes).
 */

import { writeFileSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  APPEARANCE_PRESETS,
  APPEARANCE_PRESET_ATTRIBUTE,
  APPEARANCE_TOKEN_NAMES,
  derivePresetTokens,
  type AppearancePreset,
  type AppearanceScheme,
} from "../src/shared/appearance-presets";

const OUTPUT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/ui/theme/presets.css",
);

/**
 * Two selectors per block, and both are load-bearing.
 *
 * `:root[…]` is the app-wide case — the attribute the root layout stamps on
 * `<html>`. It has to out-specify the bare `:root` palette in `globals.css`,
 * and `(0,2,0)` against `(0,1,0)` does that regardless of import order.
 *
 * The unqualified `[…]` is what makes a PREVIEW possible: any element carrying
 * the attribute re-declares the dye for its own subtree, so the settings screen
 * shows six real swatches instead of six hard-coded colours. Local declarations
 * beat inherited ones, so the nesting resolves without a specificity fight.
 *
 * Dark needs the class on BOTH forms: `:root.dark[…]` for the page itself, and
 * `.dark […]` (0,2,0) so a nested preview outranks its own light block (0,1,0).
 */
function selectorFor(preset: AppearancePreset, scheme: AppearanceScheme): string {
  const attribute = `[${APPEARANCE_PRESET_ATTRIBUTE}="${preset.id}"]`;
  return scheme === "light"
    ? `:root${attribute},\n${attribute}`
    : `:root.dark${attribute},\n.dark ${attribute}`;
}

function blockFor(preset: AppearancePreset, scheme: AppearanceScheme): string {
  const tokens = derivePresetTokens(preset, scheme);
  const declarations = APPEARANCE_TOKEN_NAMES.map(
    (name) => `  ${name}: ${tokens[name]};`,
  ).join("\n");
  return `${selectorFor(preset, scheme)} {\n${declarations}\n}`;
}

function render(): string {
  const blocks = APPEARANCE_PRESETS.flatMap((preset) => {
    const dye =
      preset.chromaScale === 1
        ? "chroma gốc"
        : `chroma ${Math.round(preset.chromaScale * 100)}% (sRGB không giữ nổi chroma gốc ở hue này)`;
    const cloth =
      preset.groundShift === 0
        ? "nền giữ nguyên bản gốc"
        : `nền xoay ${preset.groundShift}°, chroma x${preset.surfaceChromaScale} (mực x${preset.inkChromaScale}), cắt theo gamut từng lớp`;

    return [
      `/* ${preset.label} — nhuộm hue ${preset.hue}, ${dye}; ${cloth}.`,
      ` * ${preset.description} */`,
      blockFor(preset, "light"),
      blockFor(preset, "dark"),
      "",
    ];
  });

  return [
    "/*",
    " * @generated by `pnpm run theme:presets` — do not edit manually.",
    " * Source: src/shared/appearance-presets.ts",
    " *",
    " * One block per preset per scheme: the ground, every surface above it, the",
    " * ink, the hairlines and the action colour. Lightness is never re-valued —",
    " * only hue and chroma — and every status hue (lỗi, cảnh báo, thành công,",
    " * thông tin) is left exactly as the approved palette set it.",
    " */",
    "",
    ...blocks,
  ]
    .join("\n")
    .replace(/\n+$/, "\n");
}

const rendered = render();
const isCheck = process.argv.includes("--check");

if (!isCheck) {
  writeFileSync(OUTPUT_PATH, rendered, "utf8");
  console.log(`Wrote ${APPEARANCE_PRESETS.length} presets to ${OUTPUT_PATH}`);
  process.exit(0);
}

let committed: string;
try {
  committed = readFileSync(OUTPUT_PATH, "utf8");
} catch (cause) {
  console.error(`presets.css is missing (${String(cause)}). Run: pnpm run theme:presets`);
  process.exit(1);
}

if (committed !== rendered) {
  console.error("presets.css is stale — run: pnpm run theme:presets");
  process.exit(1);
}

console.log("presets.css is up to date.");
